# Generated by Django 5.2 on 2025-04-16 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_uploadedimage_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='is_ocr',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='username',
        ),
    ]
